### ISSUE TITLE
Functional components with arrow functions error

### ISSUE THREAD

**Issue by alejomo** [alexlafroscia/ember-react-components#27]
a functional component with arrow function, eg:

const Test = ({ name }) => (<p>Hello, {name}</p>)

you get this error:
component-is-functional.js:10 Uncaught TypeError: Cannot read property 'render' of undefined
    at componentIsFunctional (component-is-functional.js:10)

since arrow functions doesn't have prototype, is breaks this condition:  arg.prototype.render === undefined

as a work around I initialized Test.prototype = {} and it works.

**Comment by alexlafroscia** [comment]
> since arrow functions doesn't have prototype

That's really interesting -- I didn't know that!

I can definitely add a test case around arrow functions and get this fixed. Thanks for reporting!

**Comment by alejomo** [comment]
>  I didn't know that!

me neither :), found it in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Use_of_prototype_property

Thanks!

**Comment by alexlafroscia** [comment]
`2.0.4` should fix this up for you. Thanks for reporting!
