### ISSUE TITLE
Decorator issue, A class descriptor's .kind property must be "class"

### ISSUE THREAD

**Issue by alejomo** [alexlafroscia/ember-react-components#29]
Getting this error:
Uncaught TypeError: A class descriptor's .kind property must be "class", but a decorator created a class descriptor with .kind "undefined"
    at Object.toClassDescriptor (decorate.js:258)

when you use this syntax:
```js
@WithEmberSupport
export default class SayHi extends React.Component {...}
```

but this one works:
```js
class SayHi extends React.Component {...}
export default WithEmberSupport(SayHi)
```

dependencies installed:

"ember-cli": "~3.7.1",
"ember-decorators": "^5.1.2"
"ember-react-components": "^2.0.3",
"@ember-decorators/babel-transforms": "^3.1.5",

**Comment by alexlafroscia** [comment]
I think this is an issue around the version of `ember-decorators/babel-transforms` that this add-on was built around. I'll look into updating it to use the latest version.
