### ISSUE TITLE
JSX extensions

### ISSUE THREAD

**Issue by ahopkins** [alexlafroscia/ember-react-components#31]
Nice work. I hope you keep it up.

Any advice on an easy way to get Ember to build `.jsx` extensions instead of `.js`?

**Comment by alexlafroscia** [comment]
I think you could probably use something like `broccoli-funnel` in the `treeForApp` hook to pull in JSX files and then `merge-trees` to combine the default tree with the additional JSX files. 

I can look into whether the addon can make that work out of the box as well.

**Comment by jasonmit** [comment]
ember-cli-babel supports adding other extensions to the tree it transpiles.

```js
// ember-cli-build.js
let app = new EmberAddon(defaults, {
  'ember-cli-babel': {
    extensions: ['jsx', 'js']
  }
});
```

**Comment by ahopkins** [comment]
status? Is this released?

**Comment by alexlafroscia** [comment]
Sorry, forgot about this. `3.0.2` releasing as we speak.
