### ISSUE TITLE
Load development build of React

### ISSUE THREAD

**Issue by rps-v** [alexlafroscia/ember-react-components#46]
Hello,

Is it possible to load the development build of React instead of the production one ?

Tried to set alias via `ember-auto-import` but it did not work.
```js
autoImport: {
	alias: {
		react: 'react/cjs/react.development'
	}
}
```

Am I missing something ?

**Comment by alexlafroscia** [comment]
I don't think you're missing anything... that's how I would suggest to set that up.

Is the `cjs` build the correct one? Does it want an ESM build instead? I'm not sure what it uses by default

**Comment by rps-v** [comment]
It uses the `cjs` build.
I opened [`a related issue for ember-auto-import`](https://github.com/ef4/ember-auto-import/issues/296) and the conclusion was that an addon used in the app is changing the `NODE_ENV` to `production` even though the build is started for `development`.
I added this addon in a new project and the development build is correctly loaded. If I find the problematic addon I will reply here.

Thanks for the help !
